<?php

namespace CDO\bdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpleadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadosRepository extends EntityRepository
{
}
