<?php

namespace CDO\bdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FacturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturasRepository extends EntityRepository
{
}
