<?php

namespace CDO\bdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotorasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotorasRepository extends EntityRepository
{
}
